### ISSUE TITLE
How to use GPU to accelerate ?

### ISSUE THREAD

**Issue by kevinlemon** [AI-DI/Brancher#8]
Thank you for this interesting package.  Can we use GPU to accelerate the computation? Like "model.cuda()" in pytorch?

**Comment by LucaAmbrogioni** [comment]
Hi. yes GPU accelleration is support. My collaborator in charge of the GPU support is going to answer soon.

**Comment by Immiora** [comment]
Hi!

GPU support is provided through `torch.cuda`. Thus, the functionality is completely dependent on what `torch.cuda` provides.

Here is a simple example of how to set things up:

```
import brancher.config as cfg
cfg.set_device('gpu')
print(cfg.device)
```
I added a [working example for VAE_playground](https://github.com/AI-DI/Brancher/blob/master/examples/VAE_playground_gpu.py)

**Comment by kevinlemon** [comment]
Thank you so much!
