### ISSUE TITLE
Combine with other pytorch models？

### ISSUE THREAD

**Issue by JTigerChen** [AI-DI/Brancher#9]
In many cases, the probability model built by Brancher might be just a part of a model, which is usually built by pytorch (e.g., ResNet). How to combine them together in a simple/easy way?

**Comment by LucaAmbrogioni** [comment]
Yes you can directly plug in PyTorch models. You need to use this syntax:

from brancher import functions as BF
brancher_model = BF.BrancherFunction(pytorch_model)

This BF.BrancherFunction is a decorator that can convert any function (or class with a __call___) to a Brancher function which can be used in a Brancher model. 

You can see an example of this in our VAE example:

https://colab.research.google.com/drive/1EvQS1eWWYdVlhuoP-y1RXED9a2CNu3XQ#scrollTo=YlzVy_wzuByR

I am soon going to share a new tutorial that will include this and other deep learning related syntax.

**Comment by JTigerChen** [comment]
thanks, I can not waiting to see the tutorial!
